### ISSUE TITLE
TypeError upon completion

### ISSUE THREAD

**Issue by ahuang11** [PrefectHQ/prefect-ray#22]
Unsure why this is crashing at the end. @desertaxle @madkinsz thoughts?

```
import time

from prefect import flow, task
from prefect_ray import RayTaskRunner

@task
def shout(number):
    time.sleep(0.5)
    print(f"#{number}")

@flow(task_runner=RayTaskRunner)
def count_to(highest_number):
    for number in range(highest_number):
        shout.submit(number)

if __name__ == "__main__":
    count_to(3)

# outputs
#0
#2
#1
```

```
(begin_task_run pid=67366) #1
(begin_task_run pid=67368) #0
(begin_task_run pid=67371) #2
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?3eba7a16-fd78-43e7-8929-666909e5d171)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/andrew/Applications/python/prefect-dask/prefect_dask/test.ipynb Cell 2 in <cell line: 16>()
     [14](vscode-notebook-cell:/Users/andrew/Applications/python/prefect-dask/prefect_dask/test.ipynb#ch0000001?line=13)         shout.submit(number)
     [16](vscode-notebook-cell:/Users/andrew/Applications/python/prefect-dask/prefect_dask/test.ipynb#ch0000001?line=15) if __name__ == "__main__":
---> [17](vscode-notebook-cell:/Users/andrew/Applications/python/prefect-dask/prefect_dask/test.ipynb#ch0000001?line=16)     count_to(3)

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/prefect/flows.py:367, in Flow.__call__(self, *args, **kwargs)
    364 # Convert the call args/kwargs to a parameter dict
    365 parameters = get_call_parameters(self.fn, args, kwargs)
--> 367 return enter_flow_run_engine_from_flow_call(
    368     self, parameters, return_type="result"
    369 )

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/prefect/engine.py:131, in enter_flow_run_engine_from_flow_call(flow, parameters, return_type)
    127 if in_async_main_thread():
    128     # An event loop is already running and we must create a blocking portal to
    129     # run async code from this synchronous context
    130     with start_blocking_portal() as portal:
--> 131         return portal.call(begin_run)
    132 else:
    133     # An event loop is not running so we will create one
    134     return anyio.run(begin_run)

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/anyio/from_thread.py:283, in BlockingPortal.call(self, func, *args)
    268 def call(
    269     self,
    270     func: Callable[..., Union[Coroutine[Any, Any, T_Retval], T_Retval]],
    271     *args: object
    272 ) -> T_Retval:
    273     """
    274     Call the given function in the event loop thread.
    275 
   (...)
    281 
    282     """
--> 283     return cast(T_Retval, self.start_task_soon(func, *args).result())

File ~/mambaforge/envs/ray/lib/python3.9/concurrent/futures/_base.py:446, in Future.result(self, timeout)
    444     raise CancelledError()
    445 elif self._state == FINISHED:
--> 446     return self.__get_result()
    447 else:
    448     raise TimeoutError()

File ~/mambaforge/envs/ray/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/anyio/from_thread.py:219, in BlockingPortal._call_func(self, func, args, kwargs, future)
    216             else:
    217                 future.add_done_callback(callback)
--> 219             retval = await retval
    220 except self._cancelled_exc_class:
    221     future.cancel()

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/prefect/client.py:107, in inject_client.<locals>.with_injected_client(*args, **kwargs)
    105 async with client_context as client:
    106     kwargs.setdefault("client", client)
--> 107     return await fn(*args, **kwargs)

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/prefect/engine.py:203, in create_then_begin_flow_run(flow, parameters, return_type, client)
    199     engine_logger.info(
    200         f"Flow run {flow_run.name!r} received invalid parameters and is marked as failed."
    201     )
    202 else:
--> 203     state = await begin_flow_run(
    204         flow=flow, flow_run=flow_run, parameters=parameters, client=client
    205     )
    207 if return_type == "state":
    208     return state

File ~/mambaforge/envs/ray/lib/python3.9/site-packages/prefect/engine.py:332, in begin_flow_run(flow, flow_run, parameters, client)
    329         result_storage = TempStorageBlock()
    330     flow_run_context.result_storage = result_storage
--> 332     terminal_state = await orchestrate_flow_run(
    333         flow,
    334         flow_run=flow_run,
    335         parameters=parameters,
    336         client=client,
    337         partial_flow_run_context=flow_run_context,
    338     )
    340 # If debugging, use the more complete `repr` than the usual `str` description
    341 display_state = repr(terminal_state) if PREFECT_DEBUG_MODE else str(terminal_state)

File ~/mambaforge/envs/ray/lib/python3.9/contextlib.py:670, in AsyncExitStack.__aexit__(self, *exc_details)
    666 try:
    667     # bare "raise exc_details[1]" replaces our carefully
    668     # set-up context
    669     fixed_ctx = exc_details[1].__context__
--> 670     raise exc_details[1]
...
--> 651         cb_suppress = cb(*exc_details)
    652     else:
    653         cb_suppress = await cb(*exc_details)

TypeError: 'dict' object is not callable
```

**Comment by ahuang11** [comment]
Okay, if I run in script, it works fine, but not in notebook.

**Comment by ahuang11** [comment]
Creating a new environment works.

**Comment by ahuang11** [comment]
Sometimes causes errors
```

(test_ray) [Thu 21 13:16] prefect-ray: python test.py
13:16:17.744 | INFO    | prefect.engine - Created flow run 'tungsten-mandrill' for flow 'count-to'
13:16:17.744 | INFO    | Flow run 'tungsten-mandrill' - Using task runner 'RayTaskRunner'
13:16:17.745 | INFO    | prefect.task_runner.ray - Creating a local Ray instance
13:16:20.931 | INFO    | prefect.task_runner.ray - Using Ray cluster with 1 nodes.
13:16:20.932 | ERROR   | asyncio - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<<async_generator_athrow without __name__>()> exception=KeyError(4552139968)>
Traceback (most recent call last):
  File "/Users/andrew/mambaforge/envs/test_ray/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 246, in on_shutdown
    yield
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/mambaforge/envs/test_ray/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 250, in on_shutdown
    EVENT_LOOP_GC_REFS.pop(key)
KeyError: 4552139968
13:16:20.948 | WARNING | Flow run 'tungsten-mandrill' - No default storage is configured on the server. Results from this flow run will be stored in a temporary directory in its runtime environment.
13:16:20.991 | INFO    | Flow run 'tungsten-mandrill' - Created task run 'shout-58a68b34-0' for task 'shout'
#0
13:16:21.013 | INFO    | Task run 'shout-58a68b34-0' - Finished in state Completed()
13:16:21.022 | INFO    | Flow run 'tungsten-mandrill' - Created task run 'shout-58a68b34-1' for task 'shout'
#1
13:16:21.040 | INFO    | Task run 'shout-58a68b34-1' - Finished in state Completed()
13:16:23.580 | INFO    | Flow run 'tungsten-mandrill' - Finished in state Completed('All states completed.')
```
